# Generated by Django 4.2.5 on 2023-12-16 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя автора', max_length=50, verbose_name='name author')),
                ('last_name', models.CharField(help_text='Введите фамилию автора', max_length=100, verbose_name='last_name author')),
                ('gender', models.CharField(help_text='Введите пол', max_length=50, verbose_name='gender')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(help_text='Введите название книги', max_length=50, primary_key=True, serialize=False, verbose_name='name book')),
                ('page', models.PositiveIntegerField(help_text='Введите количество страниц', verbose_name='page')),
                ('author', models.ForeignKey(help_text='Выберите имя автора книги', on_delete=django.db.models.deletion.CASCADE, to='my_project.author', verbose_name='author book')),
                ('id_user', models.ForeignKey(blank=True, help_text='выберите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id User')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя покупателя', max_length=50, verbose_name='name buyer')),
                ('last_name', models.CharField(help_text='Введите фамилию покупателя', max_length=100, verbose_name='last_name buyer')),
                ('gender', models.CharField(help_text='Введите пол', max_length=50, verbose_name='gender')),
                ('id_user', models.ForeignKey(blank=True, help_text='выберите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id User')),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название страны', max_length=50, verbose_name='name country')),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('name', models.CharField(help_text='Введите название литературы', max_length=50, primary_key=True, serialize=False, verbose_name='name literature')),
                ('buyer', models.ForeignKey(help_text='Выберите покупателя', on_delete=django.db.models.deletion.CASCADE, to='my_project.buyer', verbose_name='buyer')),
            ],
            options={
                'db_table': 'Literature',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Введите адрес', max_length=100, verbose_name='address location')),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название издательства', max_length=50, verbose_name='name publishing_house')),
            ],
            options={
                'db_table': 'Publishing',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('name', models.CharField(help_text='Введите название магазина', max_length=50, verbose_name='name store')),
                ('cost', models.PositiveIntegerField(help_text='Введите цену', verbose_name='cost')),
                ('book', models.ForeignKey(help_text='Выберите название книги', on_delete=django.db.models.deletion.CASCADE, to='my_project.book', verbose_name='book')),
                ('literature', models.ForeignKey(db_column='literature', default='Книги', help_text='Выберите литературу', on_delete=django.db.models.deletion.CASCADE, to='my_project.literature', verbose_name='literature')),
                ('location', models.ForeignKey(help_text='Выберите местоположение адреса', on_delete=django.db.models.deletion.CASCADE, to='my_project.location', verbose_name='location store')),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.AddField(
            model_name='literature',
            name='publishing',
            field=models.ManyToManyField(to='my_project.publishing'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(help_text='Выберите название издательства', on_delete=django.db.models.deletion.CASCADE, to='my_project.publishing', verbose_name='publishing_house book'),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(help_text='Выберите страну', on_delete=django.db.models.deletion.CASCADE, to='my_project.country', verbose_name='country author'),
        ),
    ]
