# Generated by Django 4.2.5 on 2023-12-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='name',
            new_name='name_literature',
        ),
    ]
